version: '3.9'

x-logging: &default-logging
  driver:     "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  voice-agent-frontend:
    container_name:       'voice-agent-frontend'
    depends_on:
      - voice-agent-backend
    platform:             linux/amd64
    restart:              always
    ports:
      - 5173:5173
    build:
      context:            .
      dockerfile:         ./Dockerfile
    logging:              *default-logging

  voice-agent-backend:
    container_name:       'voice-agent-backend'
    image:                ghcr.io/mohsennz/voice-agent-backend:latest
    pull_policy:          always # use for latest tag
    restart:              always
    # stop_grace_period:  20s
    environment:
      ASSEMBLYAI_API_KEY: put-your-own
      OPENAI_API_KEY:     put-your-own
      OPENAI_MODEL:       gpt-4o-2024-08-06

    ports:
      - 8000:8000
    logging:              *default-logging
